### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by shellscape** [fb55/domutils#131]
It would be great to have a README that enumerated the available APIs, had examples, and described the options.

**Comment by fb55** [comment]
Added docs!

**Comment by brewern** [comment]
Can we get examples for how to use some of these utils?

I'm having trouble getting the following to work:
```javascript
const handler = new DomHandler(function(err, dom) {
  const elements = findAll((elem) => (elem.type === "tag" && getAttributeValue(elem, 'data-epub-custom')), dom);
  const shortcode = parseDOM('<div>test</div>');
  elements.forEach((element) => replaceElement(element, shortcode));
});
```

I'm trying to get elements based on a data attribute, then replace each matching element. I'm returning elements, but it's mutating dom in anyway. I'm sure I'm missing how this is suppose to work.

**Comment by fb55** [comment]
@brewern Your snippet is currently not passing data to DomHandler. You could use `parseDOM` to get a DOM tree to manipulate later on (it is using DomHandler under the hood).

**Comment by NitroBAY** [comment]
> Added docs!

Maybe, it would be great to have in the readme a complete example of loading an HTML string and then appending etc. A month ago I decided to use cheerio instead of this package now I realised that it takes 1 second per document when I want to generate 700 html (SSR, I generate HTML on build time) and I would also be interested by knowing the performance differences between this package and cheerio :)
